ime = input("Dragi korisnice, reci mi svoje ime> ")
prezime = input("Dragi korisnice, reci mi svoje prezime> ")
godina_rodjenja = int(input("Dragi korisnice, reci mi godinu svog rodenja> "))
tezina = float(input("Dragi korisnice, reci mi svoju tezinu u kg> "))
drzava_rodjenja= input("Dragi korisnice, reci drzavu svog rodenja> ")
status_radnog_odnosa = input("Dragi korisnice, jesi li zaposlen (zaposlen/nezaposlen)> ")
zaposlena = bool(input("Dragi korisnice, jesi li zaposlen (True/False)> "))
spol = input("Dragi korisnice, reci svoj spol (musko/zensko)> ")

# print(ime)
print("Ime:", ime)
print("Prezime:", prezime)
print("Godina rodenja:", godina_rodjenja)
print("Tezina:", tezina, "kg")
print("Drzava rodenja:", drzava_rodjenja)
print("Sttaus radnog odnosa:", status_radnog_odnosa)
print("Zaposlena:", zaposlena)
print("Spol:", spol)