print()
print("C:\\moji podatci\\nove slike\\tajvan\\grad")
print(r"C:\moji podatci\nove slike\tajvan\grad")
print("Ivan: \"Ja sad nesto pricam.\"")
print('Ivan: "Ja sad nesto pricam."')
print(r"Ivan: \"Ja sad nesto pricam.\"")
print('Ivan: \'Ja sad nesto pricam.\'')
print("Ovoje prvi red\nOvo je drugi red\nOvo je treci red")
print("Ovoje prvi red\n\tOvo je drugi red\n\t\tOvo je treci red")
print(r"Ovoje prvi red\n\tOvo je drugi red\n\t\tOvo je treci red")
